### ISSUE TITLE
Issues met while following the tutorial

### ISSUE THREAD

**Issue by CharlieLeee** [torch-points3d/torch-points3d#543]
Hi @nicolas-chaulet 

Thanks for bringing in a framework on point cloud tasks! I followed the tutorial till [launch an experiment](https://torch-points3d.readthedocs.io/en/latest/src/tutorials.html#launch-an-experiment) and ran the following command
```
poetry run python train.py task=segmentation dataset=s3disfused model_type=pointnet2 model_name=pointnet2_charlesmsg
```
However, I got a runtime error that shows:
```
EPOCH 1 / 100
  0%|                                                                                                                                                | 0/188 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    main()
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 13, in main
    trainer.train()
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/trainer.py", line 140, in train
    self._train_epoch(epoch)
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/trainer.py", line 190, in _train_epoch
    for i, data in enumerate(tq_train_loader):
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/tqdm/std.py", line 1193, in __iter__
    for obj in iterable:
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/charlie/.cache/pypoetry/virtualenvs/torch-points3d-kJ6rdTMA-py3.6/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/datasets/base_dataset.py", line 157, in _collate_fn
    return collate_fn(batch)
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/datasets/batch.py", line 48, in from_data_list
    batch[key] = torch.stack(batch[key])
RuntimeError: stack expects each tensor to be equal size, but got [23042, 4] at entry 0 and [22564, 4] at entry 1
```
Looking forward to suggestions on fixing this error

**Comment by nicolas-chaulet** [comment]
Hi, yes you need to have samples that have the same sizes in your batch. You should use `dataset=s3disfused-fixed` instead

**Comment by CharlieLeee** [comment]
@nicolas-chaulet Thanks for the information! It worked. BTW, if I want to run pointnet2 on semantickitti, can you list out the steps I need to do to achieve that? I tried to put the entire `sequence` folder in `data/kitti/raw` folder and run the command:
```
poetry run python train.py task=segmentation dataset=semanticKitti model_type=pointnet2 model_name=pointnet2_charlesmsg
```
but it seems like the data was not read somehow.

**Comment by nicolas-chaulet** [comment]
Yes for semantic Kitti you need to download the data yourself, please
follow those instructions (it should have been printed on your terminal)
https://github.com/nicolas-chaulet/torch-points3d/blob/9966f2350e03165158ba40b9f203aae7a16d31aa/torch_points3d/datasets/segmentation/semantickitti.py#L159-L181

Le mar. 9 févr. 2021 à 10:10, Charlie Li <notifications@github.com> a
écrit :

**Comment by CharlieLeee** [comment]
@nicolas-chaulet Yes, I have already downloaded SemanticKitti, I was just wondering what exactly `rootdir` is in this tree diagram? 
```
rootdir
        └── sequences/
            ├── 00/
            │   ├── labels/
            │   │     ├ 000000.label
            │   │     └ 000001.label
            │   └── velodyne/
            │         ├ 000000.bin
            │         └ 000001.bin
            ├── 01/
            ├── 02/
            .
            .
            .
            └── 21/
```
I read from this post https://github.com/nicolas-chaulet/torch-points3d/pull/459#issuecomment-745180137 that
I should replace `rootdir` with `data/kitti/raw`, like this 
```
raw
        └── sequences/
            ├── 00/
            │   ├── labels/
            │   │     ├ 000000.label
            │   │     └ 000001.label
            │   └── velodyne/
            │         ├ 000000.bin
            │         └ 000001.bin
            ├── 01/
            ├── 02/
            .
            .
            .
            └── 21/
```
But I still get the error like this:
```
wandb: Waiting for W&B process to finish, PID 8835
y.deepcopy(self._cfg), self._dataset)
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/models/model_factory.py", line 23, in instantiate_model
    resolve_model(model_config, dataset, task)
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/utils/model_building_utils/model_definition_resolver.py", line 10, in resolve_model
    "FEAT": max(dataset.feature_dimension, 0),
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/datasets/base_dataset.py", line 48, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/charlie/Experiments/torch-points3d/torch_points3d/datasets/base_dataset.py", line 428, in feature_dimension
    return self.test_dataset[0].num_features
  File "/home/charlie/miniconda3/envs/tp/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 116, in num_features
    return self.num_node_features
  File "/home/charlie/miniconda3/envs/tp/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 111, in num_node_features
    return self[0].num_node_features
  File "/home/charlie/miniconda3/envs/tp/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 187, in __getitem__
    data = self.get(self.indices()[idx])
IndexError: range object index out of range
```

**Comment by nicolas-chaulet** [comment]
Do you have a data/kitti/processed folder? If yes delete it and try again

**Comment by CharlieLeee** [comment]
Hi @nicolas-chaulet , thanks for the reply. I deleted `data/kitti/processed` but still got the same error while running `poetry run python train.py task=segmentation dataset=s3disfused model_type=pointnet2 model_name=pointnet2_charlesmsg`. The structure of my folder looks like this:
```
(tp) ckli@ubuntu:~/Experiments/torch-points3d$ tree data/
data/
└── kitti
    └── raw
        └── sequences -> /home/charlie/Dataset/dataset/sequences

3 directories, 0 files
```

**Comment by nicolas-chaulet** [comment]
Hey, I'm sorry I don't have access to that dataset easily anymore. Were you able to fix that? The errors shows because it does not find the sequences for some reason... In principle the script should stay stuck in processing mode for quite some time.

**Comment by TommasoPappagallo** [comment]
Hello, thanks for putting up the notebooks. In PartSegmentationKPConv "!apt-get install -qq xvfb libgl1-mesa-glx" doesnt work for macos and here:
 "from torch_points3d.datasets.segmentation import ShapeNetDataset
dataset = ShapeNetDataset(params)
dataset"
I'm getting the error: 

RuntimeError: 
attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage:
  File "/Users/parrot/Envs/test2/lib/python3.7/site-packages/torch_sparse/storage.py", line 145
    def empty(self):
        self = SparseStorage.__new__(SparseStorage)
        self._row = None
        ~~~~~~~~~~~~~~~~ <--- HERE
        self._rowptr = None
        self._value = None

**Comment by mpautzke** [comment]
I'm hitting the same error when trying to run with this dataset.  Data was placed in kitti/raw/.  I deleted the processed folder but receive the same error.  As @CharlieLeee mentioned, it seems like the data is not loaded.

**Comment by nicolas-chaulet** [comment]
Ok, I found something but I don't have access to the dataset but #564 should fix that, could you please double check?

**Comment by mpautzke** [comment]
Thanks for the quick reply!  I pulled that branch in and ran but it gave the same error.  I then realized that I had to remove the processed folder and that did the trick this time.  It might be helpful to add a log statement saying something like "processed data exists, skipping processing".  I ran into another issue where it was looking for data.use_category.  Since it wasn't on the kitti config, I added it as use_category: False.  I then ran it once more and I was getting the training logout but it eventually failed on the first epoch with the error "RuntimeError: stack expects each tensor to be equal size, but got [53418, 1] at entry 0 and [60041, 1] at entry 1".  I've also tried with just one sequence folder to see if that made a difference.  Attached is an output from one of the trials.  I downloaded and merged the point data, label data, and calib data so the sequences folder 00 looks like:
/labels (4541 files)
/velodyne (4541 files)
calib.txt
poses.txt
times.txt

I could also upload the 00 folder or part of it if that would help.

[error.txt](https://github.com/nicolas-chaulet/torch-points3d/files/6152275/error.txt)

**Comment by nicolas-chaulet** [comment]
Which model are you using? What command line did you run?

**Comment by mpautzke** [comment]
Command:
python train.py task=segmentation dataset=semanticKitti model_type=pointnet2 model_name=pointnet2_charlesmsg

I also provided the full log out with print statements in the error.txt (last comment) which may give more information.

**Comment by nicolas-chaulet** [comment]
Ok, that's because you are using a dataset configuration that was writtent for Sparse convolutions or KPConv:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/conf/data/segmentation/semanticKitti.yaml

Pointnet++ takes sampels of fixed sizes as input and therefore you need to add a FixedPoint transform to the data pipeline, see this for example:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/conf/data/segmentation/scannet-fixed.yaml

More about data formats:
https://towardsdatascience.com/torch-points3d-a-unifying-framework-for-deep-learning-on-point-clouds-94115c0be4fb
