### ISSUE TITLE
KPConv Autograd Error: Computation has been modified by an inplace operation.

### ISSUE THREAD

**Issue by dgriffiths3** [torch-points3d/torch-points3d#552]
When I try to do a backward pass on a KPConv model I get the error:

```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.LongTensor [3, 25, 3]] is at version 2; expected version 1 instead.
```

After some digging, I found the tensor in question (I think) is the [`neighbourhood_features`](https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/modules/KPConv/convolution_ops.py#L95) variable which has size [3, 25, 3] using the default config. This tensor is created in the [`gather`](https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/core/common_modules/gathering.py#L31) function:. 

I can get pytorch to complete a backward pass by changing L31 from:

```
return x.gather(0, idx)
``` 

To:

```
return x.gather(0, idx.clone())
```

However, it seems odd that such a standard module would have such a large bug, which makes me think I must be doing something wrong here?

My setup is:

```
Ubuntu: 20.04
Python: 3.7
pytorch: 1.7.1
torch-points3d: 1.2.0
```

Code to replicate the error:

```
import torch
from torch_geometric.data import Batch
from torch_points3d.applications.kpconv import KPConv

pos = torch.tensor([[0.,0.,0.], [0.5,0.5,0.5], [1.,1.,1.]], requires_grad=True)
batch = torch.tensor([0, 0, 1]).long()
batch = Batch(x=pos, pos=pos, batch=batch)

kpconv = KPConv('encoder', 2, 4)
x = kpconv(batch).x

loss = (x - torch.tensor(0.)).mean()
loss.backward()
```

and the full error:

```
/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/autograd/__init__.py:132: UserWarning: Error detected in GatherBackward. Traceback of forward call that caused the error:
  File "test.py", line 12, in <module>
    x = kpconv(batch).x
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/applications/kpconv.py", line 144, in forward
    data = self.down_modules[-1](data)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/blocks.py", line 280, in forward
    data = block(data, precomputed=precomputed)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/blocks.py", line 201, in forward
    output = self.kp_conv(output, precomputed=precomputed)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/blocks.py", line 87, in forward
    x = self.kp_conv(q_pos, data.pos, idx_neighboors, data.x,)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/kernels.py", line 92, in forward
    self.aggregation_mode,
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/convolution_ops.py", line 53, in KPConv_ops
    neighbors = gather(support_points, neighbors_indices)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/core/common_modules/gathering.py", line 31, in gather
    return x.gather(0, idx)
 (Triggered internally at  /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  allow_unreachable=True)  # allow_unreachable flag
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    loss.backward()
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.LongTensor [3, 25, 3]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

**Comment by nicolas-chaulet** [comment]
Hey, I am assuming that your tensor gets empty at some point. Could you confirm? Also could you print the value of idx.size() just before L31 in the gather function? My intuition is that it is actually empty or degenerate somehow.

**Comment by dgriffiths3** [comment]
Adding this line above L31:
```

```

Gives the following output:

```
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 32]), idx: torch.Size([3, 25, 32]), gather: torch.Size([3, 25, 32])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 32]), idx: torch.Size([3, 25, 32]), gather: torch.Size([3, 25, 32])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 64]), idx: torch.Size([3, 25, 64]), gather: torch.Size([3, 25, 64])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 64]), idx: torch.Size([3, 25, 64]), gather: torch.Size([3, 25, 64])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 128]), idx: torch.Size([3, 25, 128]), gather: torch.Size([3, 25, 128])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 128]), idx: torch.Size([3, 25, 128]), gather: torch.Size([3, 25, 128])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 256]), idx: torch.Size([3, 25, 256]), gather: torch.Size([3, 25, 256])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 256]), idx: torch.Size([3, 25, 256]), gather: torch.Size([3, 25, 256])
x: torch.Size([4, 25, 3]), idx: torch.Size([3, 25, 3]), gather: torch.Size([3, 25, 3])
x: torch.Size([4, 25, 512]), idx: torch.Size([3, 25, 512]), gather: torch.Size([3, 25, 512])
/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/autograd/__init__.py:132: UserWarning: Error detected in GatherBackward. Traceback of forward call that caused the error:
  File "test.py", line 12, in <module>
    x = kpconv(batch).x
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/applications/kpconv.py", line 144, in forward
    data = self.down_modules[-1](data)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/blocks.py", line 280, in forward
    data = block(data, precomputed=precomputed)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/blocks.py", line 201, in forward
    output = self.kp_conv(output, precomputed=precomputed)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/blocks.py", line 87, in forward
    x = self.kp_conv(q_pos, data.pos, idx_neighboors, data.x,)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/kernels.py", line 92, in forward
    self.aggregation_mode,
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/modules/KPConv/convolution_ops.py", line 53, in KPConv_ops
    neighbors = gather(support_points, neighbors_indices)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch_points3d/core/common_modules/gathering.py", line 34, in gather
    return x.gather(0, idx)
 (Triggered internally at  /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  allow_unreachable=True)  # allow_unreachable flag
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    loss.backward()
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/david/data/selfpoints/env3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.LongTensor [3, 25, 3]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

It doesn't appear to be empty. I also printed out the output of `x`, `idx` and `x.gather(0, idx)` and they all have values.

**Comment by nicolas-chaulet** [comment]
That's really surprising. For example tests pass just fine and involve a forward and a backward on each model we have. So I'm inclined to think that it is coming from your dataset or somehow the error is not reported at the right place...

**Comment by dgriffiths3** [comment]
Hmm, very strange. I originally assumed it was my dataset, but I also get the same error with the minimal example I posted above.
