### ISSUE TITLE
Hi，is cuda 10.1 and driver version V10.1.243 supproted?

### ISSUE THREAD

**Issue by HuangDihe** [torch-points3d/torch-points3d#617]

**Comment by HuangDihe** [comment]
I have installed torch-points3d.
But when I `from torch_points3d.applications.pretrained_api import PretainedRegistry`
it shows 
/usr/local/lib64/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torch_points3d/applications/pretrained_api.py", line 7, in <module>
    from torch_points3d.datasets.dataset_factory import instantiate_dataset
  File "/usr/local/lib/python3.6/site-packages/torch_points3d/datasets/dataset_factory.py", line 6, in <module>
    from torch_points3d.datasets.base_dataset import BaseDataset
  File "/usr/local/lib/python3.6/site-packages/torch_points3d/datasets/base_dataset.py", line 8, in <module>
    import torch_geometric
  File "/usr/local/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/usr/local/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/usr/local/lib64/python3.6/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/usr/local/lib64/python3.6/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib64/python3.6/site-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv

Could you provide a version which supports this driver?

**Comment by CCInc** [comment]
Hi, this looks to be a pytorch issue, not a torch-points issue.

**Comment by HuangDihe** [comment]
> Hi, this looks to be a pytorch issue, not a torch-points issue.

but when I `import torch`, there is no error

**Comment by nicolas-chaulet** [comment]
I think the issue comes from `torch_sparse`, probably compiled against the wrong version of Pytorch. Checkout the README, there is a section about those kind of problems.
