### ISSUE TITLE
Setting up minimal example with RandLa-Net modules

### ISSUE THREAD

**Issue by CharlesGaydon** [torch-points3d/torch-points3d#696]
Hello,
thanks for the great repo.

I want to use RandLa-Net, but am struggling to define a minimal working example. I wanted to use the module in `torch_points3d.modules.RandLANet.modules`, which have little documentation. I understand that contrary to some other models (e.g. PointNet++), RandLa-Net is not implemented as an "application" yet, but I figured I could still use the module implementation.
However, I wonder if I am either a) using wrong input dimensions, 2) missing some parameters (like the flow for the message passing, 3) having a bad MLP definitions or 4) something else... because I am getting a dimension error (see below). 

Would you happen to know what I am missing?

Code:
```python
from torch_points3d.modules.RandLANet.modules import *
from torch_geometric.data import Data
import torch

pos = torch.Tensor(np.random.random((500, 3)))
x = torch.Tensor(np.random.random((500, 6)))
batch = torch.from_numpy(np.random.randint(size=500, low=0, high=4))  # ,dtype=np.int64)
data = Data(x=x, pos=pos, batch=batch)

indim = 6
outdim = 6
ratio = [0.25, 0.25]
point_pos_nn = [[6 + 3, 64, 64], [64 + 3, 128, 128]]
attention_nn = [[6 * 2, 64, 64], [64 * 2, 128, 128]]
down_conv_nn = [[128, 64, 64], [64, 64, 2]]
model = RandLANetRes(indim, outdim, ratio, point_pos_nn, attention_nn, down_conv_nn)
model(data)
```
Error trace:
```python
Traceback (most recent call last):  File "/home/cgaydon/Segmentation-Validation-Model/notebooks/8.0-cga-randlanet.py", line 18, in <module>
    model(data)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_points3d/modules/RandLANet/modules.py", line 123, in forward
    return self._conv.forward(data)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_points3d/core/base_conv/message_passing.py", line 243, in forward
    data = self.convs(data)  # (N', convdim)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_points3d/modules/RandLANet/modules.py", line 98, in convs
    data = self.conv1(data)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_points3d/core/base_conv/message_passing.py", line 53, in forward
    batch_obj.x = self.conv(x, (pos[idx], pos), edge_index, batch)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_points3d/modules/RandLANet/modules.py", line 67, in conv
    return self._conv(x, pos, edge_index)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_points3d/modules/RandLANet/modules.py", line 25, in forward
    x = self.propagate(edge_index, x=x, pos=pos)
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 301, in propagate
    coll_dict = self.__collect__(self.__user_args__, edge_index,
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 196, in __collect__
    data = self.__lift__(data, edge_index,
  File "/var/data/cgaydon/anaconda3/envs/working_copy/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 166, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
```
Aditionnay, when `return src.index_select(self.node_dim, index)` line is called I have (in debug mode):
![image](https://user-images.githubusercontent.com/11660435/141150643-0968311d-fd33-4d3b-a516-7d9616f53e45.png)

Here are all my torch-related package versions : 
```bash
pyg                       2.0.2           py39_torch_1.9.0_cu111    pyg
pytorch                   1.9.1           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-cluster           1.5.9           py39_torch_1.9.0_cu111    pyg
pytorch-lightning         1.3.0              pyhd8ed1ab_1    conda-forge
pytorch-metric-learning   0.9.99                   pypi_0    pypi
pytorch-scatter           2.0.9           py39_torch_1.9.0_cu111    pyg
pytorch-sparse            0.6.12          py39_torch_1.9.0_cu111    pyg
pytorch-spline-conv       1.2.1           py39_torch_1.9.0_cu111    pyg
torch-geometric           2.0.1                    pypi_0    pypi
torch-points-kernels      0.7.0                    pypi_0    pypi
torch-points3d            1.3.0                    pypi_0    pypi
torch-scatter             2.0.8                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchmetrics              0.5.1              pyhd8ed1ab_0    conda-forge
torchnet                  0.0.4                    pypi_0    pypi
torchvision               0.2.2                      py_3    pytorch
```

**Comment by CCInc** [comment]
Hi, I'm not sure the status that RandLa-Net is at. I think it is very far from being working implementation. If you want to submit a PR that would be great!
