### ISSUE TITLE
KPConv Segmentation - Runtime Error regarding Tensor Copying

### ISSUE THREAD

**Issue by harry1576** [torch-points3d/torch-points3d#700]
Hi there,

I am trying to preform a semantic segmentation with KPConv, using the following command:
`python train.py task=segmentation models=segmentation/kpconv model_name=KPDeformableConvPaper data=segmentation/shapenet-fixed`

However this fails with the following error:
`RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment`

Log:
```Error executing job with overrides: ['task=segmentation', 'models=segmentation/kpconv', 'model_name=KPDeformableConvPaper', 'data=segmentation/shapenet-fixed']
Traceback (most recent call last):
  File "train.py", line 14, in main
    trainer.train()
  File "/local/torch-points3d/torch_points3d/trainer.py", line 148, in train
    self._train_epoch(epoch)
  File "/local/torch-points3d/torch_points3d/trainer.py", line 205, in _train_epoch
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "/local/torch-points3d/torch_points3d/models/base_model.py", line 235, in optimize_parameters
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results
  File "/local/torch-points3d/torch_points3d/models/segmentation/kpconv.py", line 112, in forward
    data = self.down_modules[i](data, precomputed=self.pre_computed)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local/torch-points3d/torch_points3d/modules/KPConv/blocks.py", line 280, in forward
    data = block(data, precomputed=precomputed)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local/torch-points3d/torch_points3d/modules/KPConv/blocks.py", line 197, in forward
    output = data.clone()
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/data.py", line 190, in clone
    return copy.deepcopy(self)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/data.py", line 375, in __deepcopy__
    out.__dict__[key] = copy.deepcopy(value, memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 94, in __deepcopy__
    out._mapping = copy.deepcopy(out._mapping, memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/local/miniconda3/envs/torch-points3d/lib/python3.8/site-packages/torch/tensor.py", line 55, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Has anyone else had this issue?

Kind regards,
Harry

**Comment by SibiAkkash** [comment]
I'm getting the same error. When `data.clone()` is called in `ResnetBBlock` it shows this error.
