### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Sandeepjalui93** [torch-points3d/torch-points3d#742]
[2022-03-31 13:53:30,632][torch_points3d.trainer][INFO] - DEVICE : cpu
fatal: ':!notebooks': '':!notebooks'' is outside repository at 'C:/Users/sjalu/OneDrive/Desktop/OPS/torch-points3d'
wandb: Currently logged in as: sjalui (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.12.11
wandb: Run data is saved locally in C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\outputs\2022-03-31\13-53-30\wandb\run-20220331_135332-1k9fpop2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run iconic-elevator-24
wandb:  View project at https://wandb.ai/sjalui/default
wandb:  View run at https://wandb.ai/sjalui/default/runs/1k9fpop2
Downloading https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip
Extracting C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\data\shapenet\shapenetcore_partanno_segmentation_benchmark_v0_normal.zip
Traceback (most recent call last):
  File "train.py", line 13, in main
    trainer = Trainer(cfg)
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\torch_points3d\trainer.py", line 49, in __init__
    self._initialize_trainer()
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\torch_points3d\trainer.py", line 96, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._cfg.data)
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\torch_points3d\datasets\dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\torch_points3d\datasets\segmentation\shapenet.py", line 313, in __init__
    self.train_dataset = ShapeNet(
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\torch_points3d\datasets\segmentation\shapenet.py", line 118, in __init__
    super(ShapeNet, self).__init__(
  File "C:\Users\sjalu\AppData\Local\pypoetry\Cache\virtualenvs\torch-points3d-kU4UqPSu-py3.8\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 60, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "C:\Users\sjalu\AppData\Local\pypoetry\Cache\virtualenvs\torch-points3d-kU4UqPSu-py3.8\lib\site-packages\torch_geometric\data\dataset.py", line 83, in __init__
    self._download()
  File "C:\Users\sjalu\AppData\Local\pypoetry\Cache\virtualenvs\torch-points3d-kU4UqPSu-py3.8\lib\site-packages\torch_geometric\data\dataset.py", line 140, in _download
    self.download()
  File "C:\Users\sjalu\OneDrive\Desktop\OPS\torch-points3d\torch_points3d\datasets\segmentation\shapenet.py", line 185, in download
    os.rename(osp.join(self.root, name), self.raw_dir)
**PermissionError: [WinError 5] Access is denied: 'C:\\Users\\sjalu\\OneDrive\\Desktop\\OPS\\torch-points3d\\data\\shapenet\\shapenetcore_partanno_segmentation_benchmark_v0_normal' -> 'C:\\Users\\sjalu\\OneDrive\\Desktop\\OPS\\torch-points3d\\data\\shapenet\\raw'**

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:
wandb: Synced iconic-elevator-24: https://wandb.ai/sjalui/default/runs/1k9fpop2
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\outputs\2022-03-31\13-53-30\wandb\run-20220331_135332-1k9fpop2\logs

I have followed all the installation instruction and when I am trying to run 'poetry run python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed', the dataset is downloaded and extracted but after that I am getting above error. 

Any help is appreciated!!!

**Comment by CCInc** [comment]
Hi, That looks like an os-specific error unrelated to tp3d. I would try checking your permissions for that folder within Windows.

**Comment by CCInc** [comment]
Hi, I'm closing this issue due to inactivity, feel free to reopen.
