### ISSUE TITLE
Invalid loaded object type : NoneType

### ISSUE THREAD

**Issue by Roberto59f** [torch-points3d/torch-points3d#759]
Hello there, i am new to torch-points3d and pytorch in general
So i followed the getting started guide: https://torch-points3d.readthedocs.io/en/latest/src/gettingstarted.html
But i am stuck at the training step when i run 
```python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet-fixed```
then i get the following error:
```Laspy not available for visualization.
You must specify 'models', e.g, models=<OPTION>
Available options:
        default

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

so i add the models parameter
```python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet-fixed models=default```

but then i get the following error

```Laspy not available for visualization.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\utils.py", line 198, in run_and_report
    return func()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\hydra.py", line 100, in run
    cfg = self.compose_config(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_loader_impl.py", line 256, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_loader_impl.py", line 805, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_loader_impl.py", line 777, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_loader_impl.py", line 695, in _merge_config
    loaded_cfg, _ = self._load_config_impl(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_loader_impl.py", line 589, in _load_config_impl
    ret = self.repository.load_config(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\config_repository.py", line 45, in load_config
    ret = source.load_config(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\hydra\_internal\core_plugins\file_config_source.py", line 42, in load_config
    cfg = OmegaConf.load(f)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\omegaconf\omegaconf.py", line 263, in load
    assert isinstance(
AssertionError: Invalid loaded object type : NoneType```

**Comment by Roberto59f** [comment]
ok sry my bad i found that i was giving the wrong path to the models parameter:
this fixed it for me:
```
python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed
```
