### ISSUE TITLE
can i use non fixed datasets?

### ISSUE THREAD

**Issue by Roberto59f** [torch-points3d/torch-points3d#761]
Hello there, i am new to torch-points3d and pytorch in general
I am trying to understand the datasets (so i can start making my own dataset) . I am trying to train the shapenet dataset with PPNet
But when I run the train.py
```
python train.py task=segmentation models=segmentation/ppnet model_name=PPNet data=segmentation/shapenet visualization.activate=True
```
but then i get the following error:
```
[2022-05-31 16:27:40,705][torch_points3d.utils.colors][INFO] - Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
[2022-05-31 16:27:40,709][torch_points3d.utils.colors][INFO] - Learning Rate Scheduler: ExponentialLR({'gamma': 0.9885}, update_scheduler_on=on_epoch)
[2022-05-31 16:27:40,710][torch_points3d.utils.colors][INFO] - BatchNorm Scheduler: BNMomentumScheduler(base_momentum: 0.1, update_scheduler_on=on_epoch)
[2022-05-31 16:27:40,710][torch_points3d.utils.colors][INFO] - Accumulated gradients: None
[2022-05-31 16:27:40,711][torch_points3d.trainer][INFO] - Model size = 18453966
[2022-05-31 16:27:40,712][torch_points3d.trainer][INFO] - Dataset: ShapeNetDataset
train_pre_batch_collate_transform = None
val_pre_batch_collate_transform = None
test_pre_batch_collate_transform = None
pre_transform = Compose([
    NormalizeScale(),
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
test_transform = None
train_transform = Compose([
    RandomNoise(sigma=0.01, clip=0.05),
    RandomScaleAnisotropic([0.9, 1.1]),
])
val_transform = None
inference_transform = Compose([
    NormalizeScale(),
    GridSampling3D(grid_size=0.02, quantize_coords=False, mode=mean),
])
Size of train_dataset = 12137
Size of test_dataset = 2874
Size of val_dataset = 1870
Batch size = 16
[2022-05-31 16:27:40,715][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets:  ['test', 'val']
[2022-05-31 16:27:40,715][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  val
[2022-05-31 16:27:40,715][torch_points3d.metrics.base_tracker][INFO] - Access tensorboard with the following command <tensorboard --logdir=C:\Users\user\Documents\pytorch\torch-points3d\outputs\2022-05-31\16-27-35\tensorboard>
[2022-05-31 16:27:40,745][torch_points3d.trainer][INFO] - EPOCH 1 / 3
  1%|                    | 4/759 [05:23<16:58:38, 80.95s/it, data_loading=0.002, iteration=61.96, train_Cmiou=14.22, train_Imiou=14.13)]
Traceback (most recent call last):
  File "C:\Users\user\Documents\pytorch\torch-points3d\torch_points3d\trainer.py", line 230, in _train_epoch
    prof.step()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 259, in step
    self._start_warmup()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 355, in _start_warmup
    self.profiler = prof.profile(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\profiler.py", line 460, in __init__
    assert (
AssertionError: Requested Kineto profiling but Kineto is not available,
                  make sure PyTorch is built with USE_KINETO=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 14, in main
    trainer.train()
  File "C:\Users\user\Documents\pytorch\torch-points3d\torch_points3d\trainer.py", line 153, in train
    self._train_epoch(epoch)
  File "C:\Users\user\Documents\pytorch\torch-points3d\torch_points3d\trainer.py", line 237, in _train_epoch
    return 0
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 230, in __exit__
    self._exit_actions()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 346, in _exit_actions
    self._start_trace()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 367, in _start_trace
    assert self.profiler is not None
AssertionError

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

wandb: Waiting for W&B process to finish, PID 6740
wandb: Program failed with code 1. Press ctrl-c to abort syncing.
wandb: Syncing files in wandb\run-20220531_142735-93amxf8z:
wandb:   change.patch
wandb:   hydra-config.yaml
wandb:   overrides.yaml
wandb: plus 6 W&B file(s) and 0 media file(s)
wandb:
wandb: Synced pleasant-oath-55: https://app.wandb.ai/dronee/default/runs/93amxf8z
```
I tried it then with shapenet-fixed and then it works.
but is it possible to also use a model that doesn't require the datasets to be fixed because i would like to use pointclouds with different sizes?

**Comment by CCInc** [comment]
It looks like the error is casued by the profiling tool, can you try to run without profiling by disabling tensorboard logging? `training.tensorboard.log=False`. Also, you can try removing `visualization.activate=True` and see if that makes a difference.
