### ISSUE TITLE
'Batch' object has no attribute 'clone'

### ISSUE THREAD

**Issue by pfmephisto** [torch-points3d/torch-points3d#766]
Hi,
I seem to be running in to the same error as in #513 although as far as I can see the transforms are being set. 
But I'm not sure if they are being applied.

I am running just the standard configurations and invoking `train.py` as such:
`train.py task=segmentation models=segmentation/kpconv data=segmentation/s3disfused model_name=KPConvPaper`

```
Traceback (most recent call last):
  File "train.py", line 14, in main
    trainer = Trainer(cfg)
  File "/home/mephisto/repos/torch-points3d/torch_points3d/trainer.py", line 49, in __init__
    self._initialize_trainer()
  File "/home/mephisto/repos/torch-points3d/torch_points3d/trainer.py", line 96, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._cfg.data)
  File "/home/mephisto/repos/torch-points3d/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/home/mephisto/repos/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 643, in __init__
    self.train_dataset = dataset_cls(
  File "/home/mephisto/repos/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 510, in __init__
    super().__init__(root, *args, **kwargs)
  File "/home/mephisto/repos/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 298, in __init__
    self._load_data(path)
  File "/home/mephisto/repos/torch-points3d/torch_points3d/datasets/segmentation/s3dis.py", line 559, in _load_data
    low_res = self._grid_sphere_sampling(data.clone())
AttributeError: 'Batch' object has no attribute 'clone'
```

**Comment by CCInc** [comment]
Hi! Please let me know what version of torch-geometric you are using, it sounds like you may be using 2.0 but currently the library requires version 1.x.

**Comment by pfmephisto** [comment]
Hi @CCInc,
thanks, I am indeed using version `2.0.5`. I'll try the other one 😄
