### ISSUE TITLE
Test Run after installation

### ISSUE THREAD

**Issue by zhouenbo** [torch-points3d/torch-points3d#800]
Hi there,

I installed torch-points3d and tyr a test run with

`python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed`

But I got an error with this:

> Traceback (most recent call last):
>   File "train.py", line 14, in main
>     trainer.train()
>   File "/home/enbozhou/indoor_2023/torch-points3d/torch_points3d/trainer.py", line 147, in train
>     self._train_epoch(epoch)
>   File "/home/enbozhou/indoor_2023/torch-points3d/torch_points3d/trainer.py", line 195, in _train_epoch
>     with self.profiler_profile(epoch) as prof:
>   File "/home/enbozhou/indoor_2023/torch-points3d/torch_points3d/trainer.py", line 354, in profiler_profile
>     schedule=torch.profiler.schedule(
> TypeError: schedule() got an unexpected keyword argument 'skip_first'

Can anyone help me? @ptoews @CCInc @loicland @rancheng @Uakh

**Comment by zhouenbo** [comment]
Is this repo still in maintenance?

**Comment by mazhenyuwin** [comment]
Hi, I meet the same error, have you solved it?

**Comment by CassSarge** [comment]
Same error, hope someone can figure it out

**Comment by ZZH86** [comment]
One way to continue executing the code is to comment out the line
